import InputBar from './_components/InputBar';
import Header from './_components/Header';
import Sidebar from './_components/Sidebar';
import { NotesProvider } from './_context/NotesContext';
import './_styles/globals.css';

export const metadata = {
  title: 'Note Taking App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NotesProvider>
          <div className="grid h-screen grid-cols-[14rem_1fr] grid-rows-[auto_1fr_auto] p-2">
            <header className="col-start-2">
              <Header />
            </header>
            <aside className="col-start-1 row-span-3 row-start-1 p-2">
              <Sidebar />
            </aside>
            <main className="col-start-2 row-start-2 p-4">{children}</main>
            <footer className="col-start-2 row-start-3 pb-4">
              <InputBar />
            </footer>
          </div>
        </NotesProvider>
      </body>
    </html>
  );
}
